name: CI - Ubuntu 24.04

on:
  push:
    branches:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Release (static)
            build_type: Release
            shared_libs: OFF
          - name: RelWithDebInfo (shared)
            build_type: RelWithDebInfo
            shared_libs: ON
          - name: Debug (static)
            build_type: Debug
            shared_libs: OFF

    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        path: source

    - name: Set up Spack
      uses: spack/setup-spack@16b756799ede8b28951287f89bcd3fdb32ec1ca3 # v3.0.0
      with:
        ref: develop      # Spack version (examples: develop, releases/v0.23)
        buildcache: true  # Configure oci://ghcr.io/spack/github-actions-buildcache
        color: true       # Force color output (SPACK_COLOR=always)
        path: spack       # Where to clone Spack

    - name: Install Dependencies
      run: |
        spack -e ${{github.workspace}}/source install

    - name: Configure
      shell: spack-bash {0}
      run: |
        spack env activate ${{github.workspace}}/source
        cmake -S ${{github.workspace}}/source \
              -B ${{github.workspace}}/build \
              -GNinja \
              -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
              -DCMAKE_COMPILE_WARNING_AS_ERROR=ON \
              -DCMAKE_CXX_CLANG_TIDY="clang-tidy;-warnings-as-errors=*" \
              -DCMAKE_REQUIRE_FIND_PACKAGE_Kokkos=ON \
              -DCMAKE_REQUIRE_FIND_PACKAGE_KokkosKernels=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Test
      run: ctest --test-dir ${{github.workspace}}/build -LE Nightly --output-on-failure

    - name: Install
      run: cmake --install ${{github.workspace}}/build --prefix ${{github.workspace}}/install
